import Mock from 'mockjs'

export default {
    getBookList: () => {
        return {
            code: 200,
            data: [
                {
                    id: 1,
                    title: 'JavaScript高级编程',
                    author: 'John Resig',
                    isbn: '9787530216783',
                    publisher: '人民邮电出版社',
                    publishDate: '2019-01-01',
                    price: 69.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-1',
                    createTime: '2019-01-01 12:00:00'
                },
                {
                    id: 2,
                    title: 'Python编程从入门到实践',
                    author: 'Eric Matthes',
                    isbn: '9787530216784',
                    publisher: '人民邮电出版社',
                    publishDate: '2018-12-01',
                    price: 59.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-2',
                    createTime: '2018-12-01 12:00:00'
                },
                {
                    id: 3,
                    title: '计算机网络：自顶向下方法',
                    author: 'James F. Kurose',
                    isbn: '9787530216785',
                    publisher: '人民邮电出版社',
                    publishDate: '2018-11-01',
                    price: 79.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-3',
                    createTime: '2018-11-01 12:00:00'
                },
                {
                    id: 4,
                    title: '三体',
                    author: '刘慈欣',
                    isbn: '9787530216786',
                    publisher: '重庆出版社',
                    publishDate: '2019-02-01',
                    price: 49.9,
                    category: '2',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-4',
                    createTime: '2019-02-01 12:00:00'
                },
                {
                    id: 5,
                    title: '白夜行',
                    author: '东野圭吾',
                    isbn: '9787530216787',
                    publisher: '南海出版公司',
                    publishDate: '2018-10-01',
                    price: 39.9,
                    category: '2',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-5',
                    createTime: '2018-10-01 12:00:00'
                },
                {
                    id: 6,
                    title: '活着',
                    author: '余华',
                    isbn: '9787530216788',
                    publisher: '作家出版社',
                    publishDate: '2018-09-01',
                    price: 29.9,
                    category: '2',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-6',
                    createTime: '2018-09-01 12:00:00'
                },
                {
                    id: 7,
                    title: '编程珠玑',
                    author: 'Jon Bentley',
                    isbn: '9787530216789',
                    publisher: '人民邮电出版社',
                    publishDate: '2018-08-01',
                    price: 59.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-7',
                    createTime: '2018-08-01 12:00:00'
                },
                {
                    id: 8,
                    title: 'Java编程思想',
                    author: 'Bruce Eckel',
                    isbn: '9787530216790',
                    publisher: '机械工业出版社',
                    publishDate: '2018-07-01',
                    price: 79.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-8',
                    createTime: '2018-07-01 12:00:00'
                },
                {
                    id: 9,
                    title: 'C程序设计语言',
                    author: 'Brian Kernighan, Dennis Ritchie',
                    isbn: '9787530216791',
                    publisher: '机械工业出版社',
                    publishDate: '2018-06-01',
                    price: 69.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-9',
                    createTime: '2018-06-01 12:00:00'
                },
                {
                    id: 10,
                    title: 'C++ Primer',
                    author: 'Stanley B. Lippman',
                    isbn: '9787530216792',
                    publisher: '人民邮电出版社',
                    publishDate: '2018-05-01',
                    price: 89.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-10',
                    createTime: '2018-05-01 12:00:00'
                },
                {
                    id: 11,
                    title: '深入理解计算机系统',
                    author: 'Randal E. Bryant, David R. O\'Hallaron',
                    isbn: '9787530216793',
                    publisher: '机械工业出版社',
                    publishDate: '2018-04-01',
                    price: 99.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-11',
                    createTime: '2018-04-01 12:00:00'
                },
                {
                    id: 12,
                    title: '数据结构与算法分析',
                    author: 'Mark Allen Weiss',
                    isbn: '9787530216794',
                    publisher: '清华大学出版社',
                    publishDate: '2018-03-01',
                    price: 79.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-12',
                    createTime: '2018-03-01 12:00:00'
                },
                {
                    id: 13,
                    title: '编程之美',
                    author: 'Peter Goodliffe',
                    isbn: '9787530216795',
                    publisher: '人民邮电出版社',
                    publishDate: '2018-02-01',
                    price: 59.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-13',
                    createTime: '2018-02-01 12:00:00'
                },
                {
                    id: 14,
                    title: 'JavaScript权威指南',
                    author: 'David Flanagan',
                    isbn: '9787530216796',
                    publisher: '人民邮电出版社',
                    publishDate: '2018-01-01',
                    price: 69.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-14',
                    createTime: '2018-01-01 12:00:00'
                },
                {
                    id: 15,
                    title: 'Python核心编程',
                    author: 'Wesley J. Chun',
                    isbn: '9787530216797',
                    publisher: '人民邮电出版社',
                    publishDate: '2017-12-01',
                    price: 59.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-15',
                    createTime: '2017-12-01 12:00:00'
                },
                {
                    id: 16,
                    title: '编程之美2',
                    author: 'Anders Hejlsberg, Bruce Eckel, Herb Schildt',
                    isbn: '9787530216798',
                    publisher: '人民邮电出版社',
                    publishDate: '2017-11-01',
                    price: 79.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-16',
                    createTime: '2017-11-01 12:00:00'
                },
                {
                    id: 17,
                    title: 'C Primer Plus',
                    author: 'Stephen Prata',
                    isbn: '9787530216799',
                    publisher: '人民邮电出版社',
                    publishDate: '2017-10-01',
                    price: 89.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-17',
                    createTime: '2017-10-01 12:00:00'
                },
                {
                    id: 18,
                    title: 'Java核心技术',
                    author: 'Cay S. Horstmann',
                    isbn: '9787530216800',
                    publisher: '人民邮电出版社',
                    publishDate: '2017-09-01',
                    price: 79.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-18',
                    createTime: '2017-09-01 12:00:00'
                },
                {
                    id: 19,
                    title: '计算机程序的构造与解释',
                    author: 'Harold Abelson, Gerald Jay Sussman',
                    isbn: '9787530216801',
                    publisher: '人民邮电出版社',
                    publishDate: '2017-08-01',
                    price: 99.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-19',
                    createTime: '2017-08-01 12:00:00'
                },
                {
                    id: 20,
                    title: '数据结构与算法',
                    author: 'Alfred V. Aho, John E. Hopcroft, Jeffrey D. Ullman',
                    isbn: '9787530216802',
                    publisher: '人民邮电出版社',
                    publishDate: '2017-07-01',
                    price: 89.9,
                    category: '1',
                    stock: '100',
                    status: '1',
                    flag: '0',
                    shelfLocation: 'A1-1-20',
                    createTime: '2017-07-01 12:00:00'
                },
            ]
        }
    }
}
